SOFFTAnglaisBundle_homepage:
  pattern:  /hello/{name}
  defaults: { _controller: SOFFTAnglaisBundle:Default:index }

login:
  pattern: /login
  defaults: {_controller: SOFFTAnglaisBundle:Security:login }

login_check:
  pattern: /login_check
  
logout:
  pattern: /logout
  
SAB_create_account:
  pattern: /account/new
  defaults: { _controller: SOFFTAnglaisBundle:Security:new }
  
SAB_account_welcome:
  pattern: /account/welcome/{username}
  defaults: { _controller: SOFFTAnglaisBundle:Security:welcome }
    
SAB_liste_mot:
  pattern: /mot/liste
  defaults: { _controller: SOFFTAnglaisBundle:Mot:list }
  
SAB_view_mot:
  pattern: /mot/view/{motId}
  defaults: {_controller: SOFFTAnglaisBundle:Mot:view }
  
SAB_list_cadenas:
  pattern: /mot/liste/cadenas.json
  defaults: {_controller: SOFFTAnglaisBundle:Mot:listeMotCadenas }
  
SAB_mot_refresh:
  pattern: /mot/refreshcadenas/{motId}
  defaults: {_controller: SOFFTAnglaisBundle:Mot:refreshCadenas }
