SAB_homepage:
  pattern: /
  defaults: { _controller: SOFFTAnglaisBundle:Default:index }
  
register:
    pattern: /register
    defaults: {_controller: SOFFTAnglaisBundle:Security:register }
    
login:
    pattern: /login
    defaults: {_controller: SOFFTAnglaisBundle:Security:login }
  
logout:
  pattern: /logout
  defaults: { _controller: SOFFTAnglaisBundle:Security:logout }
  
SAB_create_account:
  pattern: /account/new
  defaults: { _controller: SOFFTAnglaisBundle:Security:new }
  
SAB_account_welcome:
  pattern: /account/welcome/{username}
  defaults: { _controller: SOFFTAnglaisBundle:Security:welcome }
  
SAB_create_mot:
  pattern: /mot/create
  defaults: { _controller: SOFFTAnglaisBundle:Mot:create }
    
SAB_liste_mot:
  pattern: /mot/liste
  defaults: { _controller: SOFFTAnglaisBundle:Mot:list }
  
SAB_view_mot:
  pattern: /mot/view/{motId}
  defaults: {_controller: SOFFTAnglaisBundle:Mot:view }
  
SAB_list_cadenas:
  pattern: /mot/liste/cadenas.json
  defaults: {_controller: SOFFTAnglaisBundle:Mot:listeMotCadenas }
  
SAB_mot_refresh:
  pattern: /mot/refreshcadenas/{motId}
  defaults: {_controller: SOFFTAnglaisBundle:Mot:refreshCadenas }
  
SAB_quizz_liste:
  pattern: /quizz/liste
  defaults: {_controller: SOFFTAnglaisBundle:Quizz:index }
  
SAB_quizz_create:
  pattern: /quizz/create
  defaults: {_controller: SOFFTAnglaisBundle:Quizz:create }
  
SAB_quizz_play:
  pattern: /quizz/play/{quizzId}
  defaults: {_controller: SOFFTAnglaisBundle:Quizz:play }
  
  
SAB_tag_liste:
    pattern: /tag/liste
    defaults: { _controller: SOFFTAnglaisBundle:Tag:list }
    
SAB_tag_create:
    pattern: /tag/create
    defaults: { _controller: SOFFTAnglaisBundle:Tag:create }
    
SAB_tag_update:
    pattern: /tag/{id}/update
    defaults: { _controller: SOFFTAnglaisBundle:Tag:update }
