parameters:
#    sofft_anglais.example.class: SOFFT\AnglaisBundle\Example

services:
    user_provider:
        class: SOFFT\AnglaisBundle\Security\Provider\UserProvider
        arguments:
            em: "@doctrine.orm.entity_manager"
            session: "@session"
