SOFFT\AnglaisBundle\Entity\User:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: [username], message:"Ce nom d'utilisateur est déjà utilisé. Veuillez en choisir un autre."}
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: [personaId], message: "Ce compte existe déjà" }
  properties:
    username:
      - NotBlank: { message: "Le nom d'utilisateur ne peut être vide"}
      - Length: {min: 3, minMessage: "Votre nom d'utilisateur doit contenir plus de trois lettres", max: 30, maxMessage: "Votre nom d'utilisateur doit contenir moins de 30 lettres" }

SOFFT\AnglaisBundle\Entity\Mot:
  constraints:
    - Callback:
        methods: [isValid]