SOFFT\AnglaisBundle\Entity\User:
  properties:
    password:
      - NotBlank: {message: "Le mot de passe ne peut être vide"}
      - MinLength: { limit: 3, message: "Votre mot de passe doit contenir plus de trois lettres" }
    username:
      - NotBlank: { message: "Le nom d'utilisateur ne peut être vide"}
      - MinLength: {limit: 3, message: "Votre nom d'utilisateur doit contenir plus de trois lettres" }