security:
    encoders:
        SOFFT\AnglaisBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
      chain_provider:
        providers: [in_memory, main]
      in_memory: 
        users:
          julien: {password: julien, roles: ROLE_USER}
      main:
        entity: { class: SOFFTAnglaisBundle:User, property: username }

    firewalls:
      secured_area:
        pattern: ^/
        form_login:
          check_path: /login_check
          login_path: /login
        logout:
          path:   /logout
          target: /login
        anonymous: ~
          #http_basic: ~
          #    realm: "Secured Demo Area"

    access_control:
      - { path: ^/, roles: ROLE_USER }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
