security:
    encoders:
        SOFFT\AnglaisBundle\Entity\User: sha1

    providers:
          entity:
            entity: { class: SOFFT\AnglaisBundle\Entity\User, property: username }

    firewalls:
      secured_area:
        
        pattern: ^/
          form_login:
            check_path: /login_check
            login_path: /login
          logout:
            path:   /demo/secured/logout
              target: /demo/
              #anonymous: ~
              #http_basic: ~
            #    realm: "Secured Demo Area"

      access_control:
       - { path: ^/, roles: ROLE_ADMIN }
      
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
