security:
    encoders:
        SOFFT\AnglaisBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
      persona:
        id: user_provider

    firewalls:
      dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

      secured_area:
        pattern: ^/
        form_login:
          check_path: /login_check
          login_path: /login
        logout:
          path:   /logout
          target: /login
        anonymous: ~
          #http_basic: ~
          #    realm: "Secured Demo Area"

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/account, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/, roles: ROLE_USER }
      
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
