security:
    encoders:
        SOFFT\AnglaisBundle\Entity\User: sha1

    providers:
          entity:
            entity: { class: SOFFT\AnglaisBundle\Entity\User, property: username }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        login:
            pattern:  ^/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            http_basic: ~
            #    realm: "Secured Demo Area"

    access_control:
     - { path: ^/, roles: ROLE_ADMIN }
      
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
