<?php

namespace SOFFT\AnglaisBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SOFFT\AnglaisBundle\Entity\User;
use SOFFT\AnglaisBundle\Entity\Quizz;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends EntityRepository
{
    
    public function getQuizzesOwnedBy(User $user) {
        $em = $this->getEntityManager();
        return $em->createQuery("SELECT q from SOFFT\AnglaisBundle\Entity\Quizz q where q.owner = :owner")
                ->setParameter('owner', $user)
                ->getResult();
    }
    
    
}