SOFFT\AnglaisBundle\Entity\Mot:
  type: entity
  table: mots
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    fr:
      type: string
      nullable: true
    en:
      type: string
      nullable: true
    explication:
      type: string
    cadenas:
      type: datetime
      nullable: true
  manyToOne:
    cadenaswho:
      targetEntity: User
      nullable: true
  manyToMany:
      tags:
          targetEntity: Tag
          
      
