SOFFT\AnglaisBundle\Entity\User:
  type: entity
  table: users
  id:
    id: 
      type: integer
      generator: {strategy: AUTO}
  fields:
    username:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255